$(".banner1").banner({
    img:["images/1.jpg","images/2.jpg","images/3.jpg","images/4.jpg","images/5.jpg","images/6.jpg","images/7.jpg"],
    btn:true,          
    list:true,         
    autoPlay:true,    
    delayTime:3000,   
    moveTime:500,       
    index:0 
})