
    $(".header-bottom").find(".li-all-type").hover(function(){
        $(".header-bottom").find(".index-type").css("display","block")
    },function(){
        $(".header-bottom").find(".index-type").css("display","none")
    })
    $(".header-bottom").find(".index-type").hover(function(){
        $(".header-bottom").find(".index-type").css("display","block")
    },function(){
        $(".header-bottom").find(".index-type").css("display","none")
    })
    $(".header-bottom").find(".col1").hover(function(){
        $(".header-bottom").find(".nav-type-list1").css("display","block")
    },function(){
        $(".header-bottom").find(".nav-type-list1").css("display","none")
    })
    $(".header-bottom").find(".nav-type-list1").hover(function(){
        $(this).css("display","block")
    },function(){
        $(this).css("display","none")
    })
    $(".header-bottom").find(".col2").hover(function(){
        $(".header-bottom").find(".nav-type-list2").css("display","block")
    },function(){
        $(".header-bottom").find(".nav-type-list2").css("display","none")
    })
    $(".header-bottom").find(".nav-type-list2").hover(function(){
        $(this).css("display","block")
    },function(){
        $(this).css("display","none")
    })
    $(".header-bottom").find(".col3").hover(function(){
        $(".header-bottom").find(".nav-type-list3").css("display","block")
    },function(){
        $(".header-bottom").find(".nav-type-list3").css("display","none")
    })
    $(".header-bottom").find(".nav-type-list3").hover(function(){
        $(this).css("display","block")
    },function(){
        $(this).css("display","none")
    })
    $(".header-bottom").find(".col4").hover(function(){
        $(".header-bottom").find(".nav-type-list4").css("display","block")
    },function(){
        $(".header-bottom").find(".nav-type-list4").css("display","none")
    })
    $(".header-bottom").find(".nav-type-list4").hover(function(){
        $(this).css("display","block")
    },function(){
        $(this).css("display","none")
    })
    $(".header-bottom").find(".col5").hover(function(){
        $(".header-bottom").find(".nav-type-list5").css("display","block")
    },function(){
        $(".header-bottom").find(".nav-type-list5").css("display","none")
    })
    $(".header-bottom").find(".nav-type-list5").hover(function(){
        $(this).css("display","block")
    },function(){
        $(this).css("display","none")
    })
    $(".header-bottom").find(".col6").hover(function(){
        $(".header-bottom").find(".nav-type-list6").css("display","block")
    },function(){
        $(".header-bottom").find(".nav-type-list6").css("display","none")
    })
    $(".header-bottom").find(".nav-type-list6").hover(function(){
        $(this).css("display","block")
    },function(){
        $(this).css("display","none")
    })
    $(".header-bottom").find(".col7").hover(function(){
        $(".header-bottom").find(".nav-type-list7").css("display","block")
    },function(){
        $(".header-bottom").find(".nav-type-list7").css("display","none")
    })
    $(".header-bottom").find(".nav-type-list7").hover(function(){
        $(this).css("display","block")
    },function(){
        $(this).css("display","none")
    })

